In [25]:
from sklearn.datasets import make_blobs
from scipy.stats import norm
from numpy import mean
from numpy import std
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/ferdinjoe/DSA206/main/candy-data.csv')

In [50]:
X = df.drop(['pluribus','competitorname'], axis=1)
y = df['pluribus']

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state =1)

In [57]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('accuracy =', accuracy_score(y_test,y_pred)*100)

[[ 6  3]
 [ 5 12]]
              precision    recall  f1-score   support

           0       0.55      0.67      0.60         9
           1       0.80      0.71      0.75        17

    accuracy                           0.69        26
   macro avg       0.67      0.69      0.68        26
weighted avg       0.71      0.69      0.70        26

accuracy = 69.23076923076923


In [58]:
svclassifier = SVC(kernel='poly', degree= 8)
svclassifier.fit(X_train, y_train)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('accuracy =', accuracy_score(y_test,y_pred)*100)

[[ 6  3]
 [ 5 12]]
              precision    recall  f1-score   support

           0       0.55      0.67      0.60         9
           1       0.80      0.71      0.75        17

    accuracy                           0.69        26
   macro avg       0.67      0.69      0.68        26
weighted avg       0.71      0.69      0.70        26

accuracy = 69.23076923076923


In [59]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('accuracy =', accuracy_score(y_test,y_pred)*100)

[[ 6  3]
 [ 1 16]]
              precision    recall  f1-score   support

           0       0.86      0.67      0.75         9
           1       0.84      0.94      0.89        17

    accuracy                           0.85        26
   macro avg       0.85      0.80      0.82        26
weighted avg       0.85      0.85      0.84        26

accuracy = 84.61538461538461
